#!/usr/bin/env php
<?php
namespace think;

if (version_compare(PHP_VERSION, '8.0.0', '<')) {
    die('require PHP >= 8.0 !');
}

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 应用初始化
(new App())->console->run();